![sslogo](https://github.com/stratascratch/stratascratch.github.io/raw/master/assets/sslogo.jpg)

# Intro to NumPy

NumPy is the fundamental package for scientific computing in Python. NumPy is used in many other packages in python even though you may not see it explicitly running in your code.

It is a python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.




#### Import the numpy package

In [0]:
import numpy as np

#### Make an array from a list. 

This will create a numpy array with 3 elements. 

Each numpy array contains an attribute called `shape`. Shape is a tuple which tells you how many elements you have per axis. For example (5, 6, 8) means 5 elements per axis 0, 6 elements per axis 1 and 8 elements per axis 2. Usually you will have only one or two axes.

The shape for the array in this section is `(3, )`. The reason for this funny notation is python's type system where shape must be a tuple and this is a tuple with 1 element. Writing just 3 would mean a number, not a tuple.

To verify that try `np.array([1, 2, 3]).shape` 

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

#### Make an array from a list of lists

The shape of this array is (2, 2) so this is a matrix.

In [3]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

#### Make an array using a function

The arrays made in previous sections were based on us supplying each value.

Very often we need large arrays and it is not possible to use our current approach and thus we need to use array creating functions. The most important functions are `zeros` and `ones`. They both take a parameter called shape which determines the shape of the output array.
* `zeros` makes an array which is all 0 [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)
* `ones`  makes an array which is all 1 [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones)

In [4]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### Make an array by starting at 0, incrementing by 2 and ending before 10

`arange` is the exact same thing as regular python `range` except giving back a numpy array.

This functions requires only a single argument which is the end point. The start point is assumed to be 0 and step is assumed to be 1.

In this variety when in takes three parameters, the first one is the start, second one is the end and the third one is the step.

[docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

#### Make an array of four evenly spaced numbers including both endpoints

In [7]:
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

#### Make an array of random numbers (using a normal distribution)

The random submodule of numpy contains a variety of functions for generating random numbers following a specified probability distributions or sampling from a finite set of choices. To learn more about it visit the [documentation](https://docs.scipy.org/doc/numpy/reference/routines.random.html). 

In [0]:
mean = 10
stdev = 3
number_values = 20
np.random.normal(mean, stdev, number_values)

## Indexing Arrays
#### Access elements of a 1-dimensional array.  Get the first and last element.

In python as is in many other programming languages all arrays start from 0 so the first element is at position 0.

To access the last element we can use -1 as the index. `x[-1]` is identical to `x[x.shape[0] - 1]` where `shape[0]` is the length of the array.

In [8]:
x = np.arange(4)

print(x[0])
print(x[-1])

0
3


#### Reshape an array

Remember that shape is the fundamenal property of each array and we can modify it as we desire and we often do so. To change the shape of an array we use the `reshape` method.

The code in this example creates an 1D-array of 6 elements using the `arange` functon.

We convert it to a 2D-array using the `reshape` method.

You see that the total amount of numbers did not change, only our view of them. 6 elements in a vector or 3 x 2 elements in a matrix.

It is very important that when using `reshape` to ensure that dimensions match or you will get an error. 6 = 3 x 2 is a match so this works but trying np.arange(6).reshape(4, 2) will give you an error. 

[docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

In [9]:
x = np.arange(6).reshape(2, 3)
print(x)

[[0 1 2]
 [3 4 5]]


#### Get the last row

When dealing with arrays which are of more than a single dimension we can use partial indexing specifications go slice the array the way we want. 

For example `print(x[-1])` will print the last **row**.

To get the last column take the transpose of the 2d-array and then use [-1]. 

For exampe `print(x.T[-1])` will give you the last columns. `x.T` is the transpose of `x`

In [11]:
print(x[-1, :])

[3 4 5]


#### Get the last element of the last row

Here we are using full indexing to get a single **element**.

In [12]:
print(x[-1, -1])

5


#### Get elements like a list

Using the notation `a:b` we can slice arrays as precisely as we want.

`a:b` means give me back all elements whose positions is in that set.

For example `y = [1, 3, 5, 7, 9]` and `y[0:2]` would give us the first two elements `[1, 3]`.

Negative indices mean from back so -3 means 3 positions starting from the last position.

Experiment with the values until you get the feel for it.

In [13]:
x = np.arange(10) 

print(x)
print(x[:3])
print(x[1:4])
print(x[-3:])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[1 2 3]
[7 8 9]


#### Get all elements in reverse order

The enhanced slicing syntax is `a:b:c` were `c` is the step. For example `0:10:2`.

If we omit `a` and `b` we always asume they are `a` = 0 and `b` = length of the list so we are only left with a step.

Thus `::2` means slicing from 0 to end with a step 2. `::3` mean slicing with a step 3.

Now what if we used negative steps. Using -1 as the step would reverse the logic and `a` becomes the end of the list and `b` becomes zero. So `::-1` will slice in reverse direction.

Finally there is also the slice form `::1` or written short `:` which means give me back all elements in order as they are present.

In [14]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


#### Get every second element or third element

In [15]:
print(x[::2])
print(x[::3])

[0 2 4 6 8]
[0 3 6 9]


#### Create a 5x5 matrix

In [16]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### Get the first two columns and the first two rows

Until now you have learned how to slice on a 1D array but slices can be generalized to any dimensional arrays.

The trick is to create a slice for every dimensions. 

In this example we have a 2d-array so we create two slices, one for dimension 0 (rows) and one for dimension 1 (columns)


In [0]:
print(x[:2, :2])

#### Get every second column of every second row

In [0]:
print(x[::2, ::2])

## Access parts of an array with index arrays

#### Generate six random integers between 0 and 9 inclusive

`randint` in `np.random` is a very useful function which generates uniformly distributed random integers from the range provided as its first two parameters (start and end of range respectively). It's third parameter tells the method how many numbers we need.

In [17]:
x = np.random.randint(0, 10, 6) 
print(x)

[8 4 8 4 2 2]


#### Get the first number and the last two numbers

Slices are inhetently linear and give us access to arrays in a linear fashion.

To access elements in any order we must use index arrays which are numpy arrays holding integer numbers which tell what elements to chose from the indexed array.

In [18]:
indices = [0, -2, -1]
print(x[indices])

[8 2 2]


#### Create two arrays

The array `x2` is created as `x1 * -1`. The multiplication operator here means multiply all elements of `x1` with -1 and give back that as result.

In [19]:
arrayLength = 5
x1 = np.arange(arrayLength)
x2 = np.arange(arrayLength) * -1

print(x1)
print(x2)

[0 1 2 3 4]
[ 0 -1 -2 -3 -4]


#### Create a random shuffled range of numbers

This and the following example shows how to shuffle an array in numpy.

Shuffling means reoreding the items in an array and we can do that using random permutations of the array positions.

In [25]:
indices = np.random.permutation(arrayLength)
print(indices)

[3 0 2 4 1]


#### Use indices to re-order arrays

In [28]:
print(x1[indices])
print(x2[indices])

[3 0 2 4 1]
[-3  0 -2 -4 -1]


#### Create array of boolean values

The main novelty of this example is `print(x > 2)`.

`x > 2` generates an array of boolean values where each element is True or False.
Having True at position i of the output means that the conditions is satisfied for the element of `x` at position i.

For exampe if `x=[0,1,2,3,4]` then `x > 2` would be `[False, False, False, True, True]`.

As you see 0 > 2 = False, 1 > 2 = False, 2 > 2 = False, 3 > 2 = True and 4 > 2 = True and that is shown in the output array.

In [29]:
x = np.arange(5)
print(x)
print(x > 2)

[0 1 2 3 4]
[False False False  True  True]


#### Use boolean values to index arrays

Once we have created our boolean array we can use it to index other arrays.

The rule is very simple. If at position i of index we have True include `x[i]` in the output.

In [31]:
print(x[x > 2])
print(x[np.array([False,False,False,True,True])])

[3 4]
[3 4]


## Array Math

#### Try adding to a list

In [32]:
x = [1, 2, 3, 4]

print(x + 10)

TypeError: ignored

#### Try again with an array

When trying with a list you got an error because simple python lists do not support addition with scalars.

But numpy arrays do allow that.

In [33]:
x = np.array(x)

print(x)
print(x + 10)

[1 2 3 4]
[11 12 13 14]


## Exercises

#### Create an array from 0 to 26 assign it to a variable x

In [34]:
x = np.arange(0,26)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]


#### Reverse the order of the array and print it out

In [36]:
x[::-1]

array([25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1,  0])

#### Convert the 1-dimensional array you created into a 3 dimensional array

In [44]:
x = np.arange(24)
print("1D: ", x)

a = x.reshape(4,3,2)
print(a)

1D:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


#### Find the index (location) for value 12

In [47]:
a[2,0][0]

12

#### Create a random shuffled list of values from 0-19 and assign it to variable y

In [55]:
y = np.random.randint(0,19,7)
print(y)

[ 9  1 18  2  7 10  9]


#### Create an array of boolean values for values in y that are greater than 10

In [57]:
print(y>10)


mean = 10
stdev = 3
number_values = 20
np.random.normal(mean, stdev, number_values)

[False False  True False False False False]


#### Create a random sample of 20 data points from a normal distribution with mean of 10 and standard deviation 5

In [58]:
mean = 10
std = 5 
number_values = 20
np.random.normal(mean,std, number_values)

array([ 9.27008531, 14.70509183,  3.50397716, 11.6170424 ,  9.43313079,
       12.89867653, 14.7676679 ,  9.98835423,  8.78753384,  9.33168747,
        3.38924298, 14.1046417 ,  2.29781218, 15.4015152 ,  9.83938634,
        9.66658002, 17.53187876, 13.70669406, 14.00877505,  7.32610048])